//
// DefaultAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire

extension SwaggerClientAPI {
    
    public class DefaultAPI: APIBase {
    
        /**
         
         - GET /hello/{name}
         - greets the lucky user
         - examples: [{contentType=application/json, example={
  "message" : "aeiou"
}}]
         
         - parameter name: (path) name of user to greet

         - returns: RequestBuilder<Inline_response_200> 
         */
        public class func greetUser(name name: String) -> RequestBuilder<Inline_response_200> {
            var path = "/hello/{name}"
            path = path.stringByReplacingOccurrencesOfString("{name}", withString: "\(name)", options: .LiteralSearch, range: nil)
            let URLString = SwaggerClientAPI.basePath + path
            
            let nillableParameters: [String:AnyObject?] = [:]
            let parameters = APIHelper.rejectNil(nillableParameters)

            let requestBuilder: RequestBuilder<Inline_response_200>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

            return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
        }
    
        /**
         
         - GET /sum/{first}/{second}
         - sums two numbers
         - examples: [{contentType=application/json, example={
  "message" : "aeiou"
}}]
         
         - parameter first: (path) first number
         - parameter second: (path) second number

         - returns: RequestBuilder<Inline_response_200> 
         */
        public class func sumTwo(first first: Int, second: Int) -> RequestBuilder<Inline_response_200> {
            var path = "/sum/{first}/{second}"
            path = path.stringByReplacingOccurrencesOfString("{first}", withString: "\(first)", options: .LiteralSearch, range: nil)
            path = path.stringByReplacingOccurrencesOfString("{second}", withString: "\(second)", options: .LiteralSearch, range: nil)
            let URLString = SwaggerClientAPI.basePath + path
            
            let nillableParameters: [String:AnyObject?] = [:]
            let parameters = APIHelper.rejectNil(nillableParameters)

            let requestBuilder: RequestBuilder<Inline_response_200>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

            return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
        }
    
    }
}
